BaseUrl: "http://healthsquare.com.au"
LanguageCode: "en-us"
Title: "Healthsquare"

Params:
  Author: "Your name."
  DateForm: "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID: "Your ID."
  Facebook: "Your ID."
  Twitter: "Your ID."
  Github: "Your ID."
  ShowRelatedPost: True
  Disqus: "aushealthcare."
  SyntaxHighlightTheme: "solarized_dark.min.css"

Indexes:
  tag: "tags"

permalinks:
  post: /blog/:year/:month/:day/:title/

MetadataFormat: "yaml"

